add news of Zedong's arrival and MindtPy abstract
bernalde/bernalde.github.io pull request #11
Opened 2023-08-07 15:50 UTC by ZedongPeng

2023-08-08 15:01 UTC, bernalde commented on _posts/2023-08-01-Zedong.md
> +
This is a great description. Include as much more detail as you want (you are interested in pursuing a job in academia in China, you'll be working on MINLP algorithms and software)

2023-08-09 16:58 UTC, ZedongPeng commented on _posts/2023-07-01-MindtPy.md
> +description: 'The MindtPy abstract accecpted'
Good suggestion. Thanks.

2023-08-09 18:08 UTC, ZedongPeng commented on _posts/2023-03-08-APS.md
>  description: 'My most recent conference attendance'
Should we change it to only "conference attendance"?

2023-08-11 21:15 UTC, bernalde requested changes

2023-08-11 21:15 UTC, bernalde commented on _posts/2023-03-08-APS.md
>  description: 'My most recent conference attendance'
Yes

2023-08-11 21:15 UTC, bernalde commented on _posts/2023-07-01-MindtPy.md
> +The abstract of MindtPy has been accepted to both [2023 AIChE Annual Meeting](https://www.aiche.org/conferences/aiche-annual-meeting/2023?gclid=Cj0KCQjwrMKmBhCJARIsAHuEAPR5h2LVn51eow9v9Vkcsy4C0goZVon
Link MindtPy to the documentation of Pyomo

2023-08-11 21:15 UTC, bernalde commented on _posts/2023-08-01-Zedong.md
> +
Link your name to the page where your profile is

2023-08-15 02:43 UTC, bernalde approved these changes

2023-08-15 02:44 UTC, merged